Repository recodehive/awesome-github-profiles, pull requests merged in 2024-10, with the labels that each got.

#551 Fix issue with overlapping social icons on gh-pages
  styles/styles.css
Labels: level1, gssoc-ext

#566 fixed subheading font color for light theme on gh-pages
  pages/githubbadge.html
  styles/githubbadge.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#573 updated the email address of the admin in readme file.
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#618 remove my duplicate image
  README.md
Labels: gssoc-ext, hacktoberfest-accepted

#643 bugfix: add correct GitHub url
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#646 Updated X[Twitter] logo.
  index.html
  styles/styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#674 Remove Siraj from Profiles
  .all-contributorsrc
  screenshots/Siraj01576.png
Labels: level2, gssoc-ext, hacktoberfest-accepted

#686 achievement startStruck
  pages/githubbadge.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#691 Update "How to Get" Section for "YOLO" Badge
  pages/githubbadge.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#706 [fix] correct readme on main branch for easier instructions, create CONTRIBUTING.md file
  CONTRIBUTING.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#697 added 2 more rows in each page
  scripts/retriveprofile.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#715 Added profile modal popup
  index.html
  scripts/profileModal.js
  styles/modal.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#774 Fixes In Modal : Visibility and Modal Closing on Outside Click | Issue #749
  scripts/dark-mode.js
  scripts/retriveprofile.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#773 Fixes #763: Bug Fixed and Added Back to Blogs Button
  pages/saved-blogs.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#802 popup overflow issue solved
  styles/blog.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#801 Consistent scroll issue on all pages resolved
  index.html
  pages/events.html
  scripts/ScrollToTop.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#809 Fixes the Likes Functionality | Issue #785
  scripts/retriveprofile.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#799 FIXED THE SIDE ICON ISSUE
  index.html
  styles/styles.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#861 Added Contact Form
  pages/help.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#818 ADDED THE TRANSLATOR FUNCTION
  index.html
  login.html
  pages/blog.html
  pages/compare.html
  pages/events.html
  pages/githubbadge.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#848 Microphone Fixes | Issue #811
  styles/speech.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#832 Added Frame to Contributor's Images | Added Undragability | Issue #813
  styles/compare.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#855 [fix] change the UnLiked text
  scripts/retriveprofile.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#850 [fix] toggle button change theme for mobile
  index.html
  scripts/dark-mode.js
  styles/styles.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#895 CHANGED THE FONTS
  dashboard.css
  login.css
  styles/blog.css
  styles/compare.css
  styles/construction.css
  styles/events.css
  styles/explore.css
  styles/githubbadge.css
  styles/hamburger.css
  styles/help.css
  styles/modal.css
  styles/pagination.css
  styles/speech.css
  styles/styles.css
Labels: gssoc-ext, hacktoberfest-accepted, Level 2

#929 Changed twitter logo which is not displaying previously.
  index.html
  styles/styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#925 FIxes #911: updated Social media icons
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#952 autocomment-issue-raise.yml added
  .github/workflows/autocomment-issue-raise.yml
Labels: level2, gssoc-ext, hacktoberfest-accepted

#965 Issue #946 was resolved
  styles/styles.css
Labels: level1, gssoc-ext

#991 Add Gradient to the progress bar
  styles/styles.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1010 add enhance/button-style-improve branch
  index.html
  scripts/retriveprofile.js
  styles/pagination.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1009 Twitter Logo issue changed
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1030 Update .all-contributorsrc
  .all-contributorsrc
Labels: level3, gssoc-ext, hacktoberfest-accepted

#1004 Achievement Page update #2
  pages/githubbadge.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1065 Minimum password issue #1053 fixed
  login.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1073 [fix] add Login Section and Dark Mode Button on Events and Blogs Pages
  pages/blog.html
  pages/events.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1061 Added validation for username and e-mail
  login.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1094 Add Github stats page for personalised user experience
  index.html
  pages/stats.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#1149 Update README.md
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1060 fixes #1036
  CONTRIBUTING.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1108 Made Mobile Navbar consistent
  pages/blog.html
  pages/compare.html
  pages/events.html
  pages/exploremore.html
  pages/faq.html
  pages/help.html
  pages/saved-blogs.html
  styles/hamburger.css
  styles/styles.css
Labels: level2, gssoc-ext, hacktoberfest-accepted
