Repository recodehive/awesome-github-profiles, pull requests merged in 2024-08, with the labels that each got.

#21 Need Dark Mode for this Theme: #11
  index.html
Labels: gssoc, level2

#24 Change the add you repo to middle before search button
  index.html
Labels: gssoc, level2

#40 added multiple workflows
  .github/workflows/autocomment-iss-close.yml
  .github/workflows/close-old-issue.yml
  .github/workflows/close-old-pr.yml
Labels: gssoc, level2

#33 Add sun and moon icons to dark mode toggle for improved UI
  dark-mode.js
  index.html
  styles.css
Labels: gssoc, level2

#50 Update README.md
  README.md
Labels: gssoc, level1

#55 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc, level1

#56 Added navbar wih Blog button
  assets/recode-hive.png
  index.html
  styles.css
Labels: gssoc, level1

#65 Want to make scrollable profile image where #30
  retriveprofile.js
  styles.css
Labels: gssoc, level3

#70 Added Hovering Effect to the Options
  styles.css
Labels: gssoc, level1

#80 Fixed responsiveness Of the footer sections
  styles.css
Labels: gssoc, level2

#89 Need to change the text on footer #82
  index.html
Labels: gssoc, level1

#97 Added Event page and done migration of styles
  events.css
  events.html
  githubbadge.css
  githubbadge.html
  index.html
  styles.css
Labels: gssoc, level3

#98 Changed color of footer
  styles.css
Labels: gssoc, level1

#104 Added Link for home when clicking on logo
  events.html
  exploremore.html
  githubbadge.html
  index.html
  styles.css
Labels: gssoc, level1

#107 Added Events
  events.html
Labels: gssoc, level1

#115 Enhance Social Media Icons with Hover Animation
  index.html
  styles.css
Labels: gssoc, level2

#116 Fixed structure Of html and css files
  assets/styles/events.css
  assets/styles/explore.css
  assets/styles/githubbadge.css
  assets/styles/styles.css
  pages/events.html
  pages/exploremore.html
  pages/githubbadge.html
  pages/index.html
Labels: gssoc, level1

#117 Add Scroll-to-Top Button with Hover Effects and Dark Mode Support
  ScrollToTop.js
  exploremore.html
  githubbadge.html
  index.html
  styles.css
Labels: gssoc, level2

#123 Added No Profile Found
  index.html
  retriveprofile.js
Labels: gssoc, level1

#124 Added Tools In the Navbar
  events.html
  exploremore.html
  githubbadge.html
  index.html
Labels: gssoc, level1

#137 Feature: IN DEPLOYED LINK IMAGES OF GITHUB-BADGE IS NOT WORKING #129
  .github/ISSUE_TEMPLATE/add_profile.md
  .github/workflows/update-categories.yml
  .github/workflows/update-contributors.js
  githubbadge.html
  screenshots/nishant0708.png
Labels: gssoc, level2

#136 Search bar
  index.html
  styles.css
Labels: gssoc, level1

#150 ✔️ Styled the Vertical Scrollbar of Website
  styles.css
Labels: gssoc, level2

#146 Feature: Want to Add View Count in each Profile #58
  index.html
  retriveprofile.js
  styles.css
Labels: gssoc, level3

#145 ✔️Added Favicons To The Website
  assets/achievement-png.png
  assets/blog-png.png
  assets/code-of-conduct.png
  assets/events.png
  blog.html
  events.html
  exploremore.html
  githubbadge.html
  index.html
Labels: gssoc, level3

#140 Create close-iss-on-merge.yml
  .github/workflows/close-iss-on-merge.yml
Labels: gssoc, level1

#151 Fix "Recode Hive" Text Visibility in Dark Mode on Blog
  styles.css
Labels: gssoc, level2

#170 Added sort feature on the basis of views
  index.html
  retriveprofile.js
  styles.css
Labels: gssoc, level3

#171 Removed Listing
  events.html
  exploremore.html
  githubbadge.html
  index.html
  retriveprofile.js
  styles.css
Labels: gssoc, level1

#174 Added Learn github from scratch sections in Blogs and Github Badge Page
  blog.css
  blog.html
  githubbadge.css
  githubbadge.html
Labels: gssoc, level3

#175 Added Help Page
  blog.css
  blog.html
  events.html
  githubbadge.css
  githubbadge.html
  help.css
  help.html
  index.html
  screenshots/sanjay-kv.png
  screenshots/vishanurag.png
Labels: gssoc, level3

#176 Made the tables responsive of github-badges page.
  githubbadge.html
Labels: gssoc, level2

#189 Changed the name blog to learn in navbar
  index.html
  pages/blog.html
  pages/events.html
  pages/exploremore.html
  pages/githubbadge.html
  pages/help.html
Labels: gssoc, level1

#218 ✔️Implemented "Hamburger menu" and Made it Responsive !
  index.html
  pages/blog.html
  pages/events.html
  pages/exploremore.html
  pages/githubbadge.html
  scripts/hamburger.js
  styles/hamburger.css
Labels: gssoc, level2

#208 Added Likes Feature
  scripts/retriveprofile.js
  styles/styles.css
Labels: gssoc, level3

#224 Fixed the badges icon colour for dark & light mode
  pages/githubbadge.html
Labels: gssoc, level2

#236 Made the blog page & github badges page responsive
  pages/githubbadge.html
  styles/blog.css
  styles/styles.css
Labels: gssoc, level2

#249 Nav bar is not consistent across on the pages. #245
  index.html
  pages/blog.html
  pages/compare.html
  pages/events.html
  pages/exploremore.html
  pages/githubbadge.html
  pages/help.html
  styles/hamburger.css
Labels: gssoc, level2

#250 Stretched view on learn page and github badge page #244
  styles/blog.css
  styles/githubbadge.css
Labels: gssoc, level2

#251 Popup Fixed
  styles/blog.css
Labels: gssoc, level2

#267 Fixed filter box style for dark mode
  styles/styles.css
Labels: gssoc, level3

#266 Added Validation on views to count One view per browser
  scripts/retriveprofile.js
Labels: gssoc, level2

#265 Added Saved Blog Functionality
  pages/blog.html
  pages/saved-blogs.html
  scripts/blog.js
  styles/blog.css
Labels: gssoc, level2

#264 Added Tilt Effect to the images
  pages/blog.html
  pages/githubbadge.html
Labels: gssoc, level2

#261 Added profile filtering based on likes
  index.html
  scripts/retriveprofile.js
Labels: gssoc, level3

#281 Created Toast Notification
  index.html
  pages/blog.html
  scripts/blog.js
  scripts/retriveprofile.js
  styles/blog.css
  styles/styles.css
Labels: gssoc, level3

#285 added content in help page
  assets/c1.png
  assets/c2.png
  assets/c3.png
  assets/c4.png
  assets/c5.png
  assets/c6.png
  assets/c7.png
  pages/help.html
  styles/help.css
Labels: gssoc, level3

#292 FIxed profile card changing design when Adding filter options
  scripts/retriveprofile.js
Labels: gssoc, level2

#290 Fixes color of toast
  styles/styles.css
Labels: gssoc, level2

#294 Added cursor pointer to the Toggle switch icon
  styles/styles.css
Labels: gssoc, level2

#293 Added a Feature to unsave the blog
  scripts/blog.js
Labels: gssoc, level2

#296 Fixed least Likes and Most Likes Filtering
  index.html
  scripts/retriveprofile.js
Labels: gssoc, level3

#300 Made the help page responsive.
  styles/help.css
Labels: gssoc, level2

#307 Events timeline animation fixed
  pages/events.html
  styles/events.css
Labels: gssoc, level2

#303 Made the Hamburger Button of navbar functional on Help page.
  pages/help.html
Labels: gssoc, level2

#308 Removed duplicate links from navbar of exploremore page.
  pages/exploremore.html
Labels: gssoc, level2
